import { getData, saveData } from '../utils/storage.js';
import { DEFAULT_SETTINGS, isSupportedUrl, makeId, normalizeUrl } from '../utils/helpers.js';

const $=id=>document.getElementById(id);let data;
function toast(message,error=false){const t=$('toast');t.textContent=`${error?'⚠':'✓'} ${message}`;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2200)}
function applyTheme(){const theme=data.settings.theme||'system';const dark=theme==='dark'||(theme==='system'&&window.matchMedia('(prefers-color-scheme: dark)').matches);document.documentElement.dataset.theme=dark?'dark':'light'}
function loadSettings(){const s={...DEFAULT_SETTINGS,...data.settings};applyTheme();['askBeforeDelete','preventDuplicateUrls','openInNewWindowByDefault','showWebsiteCount','showLastOpened'].forEach(k=>$(k).checked=Boolean(s[k]));document.querySelector(`input[name="theme"][value="${s.theme}"]`).checked=true}
function readSettings(){return{askBeforeDelete:$('askBeforeDelete').checked,preventDuplicateUrls:$('preventDuplicateUrls').checked,openInNewWindowByDefault:$('openInNewWindowByDefault').checked,showWebsiteCount:$('showWebsiteCount').checked,showLastOpened:$('showLastOpened').checked,theme:document.querySelector('input[name="theme"]:checked')?.value||'system'}}
$('save').onclick=async()=>{try{data.settings=readSettings();await saveData(data);applyTheme();toast('Settings saved')}catch(e){console.error(e);toast(e.message,true)}};
$('export').onclick=()=>{const payload={version:1,exportedAt:Date.now(),capsules:structuredClone(data.capsules)};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='chrome-capsules.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Capsules exported')};
$('import').onclick=()=>$('file').click();
$('file').onchange=async()=>{const file=$('file').files[0];if(!file)return;try{const parsed=JSON.parse(await file.text());if(parsed.version!==1||!Array.isArray(parsed.capsules))throw new Error('Invalid capsule file.');const valid=parsed.capsules.filter(isValidCapsule);if(valid.length!==parsed.capsules.length)throw new Error('Invalid capsule file: one or more capsules are malformed.');const existingNames=new Set(data.capsules.map(c=>c.name.toLowerCase()));for(const c of valid){let name=c.name,n=2;while(existingNames.has(name.toLowerCase()))name=`${c.name} Copy ${n++}`;existingNames.add(name.toLowerCase());data.capsules.push({...c,id:makeId('capsule'),name,updatedAt:Date.now(),websites:c.websites.map((w,i)=>({...w,id:makeId('site'),order:i}))})}await saveData(data);toast(`${valid.length} capsule${valid.length===1?'':'s'} imported`)}catch(e){console.error(e);toast(e.message||'Invalid capsule file.',true)}$('file').value=''};
function isValidCapsule(c){return c&&typeof c==='object'&&typeof c.name==='string'&&c.name.trim()&&Array.isArray(c.websites)&&c.websites.every(w=>w&&typeof w.url==='string'&&isSupportedUrl(w.url))}
$('deleteAll').onclick=async()=>{if(!confirm('Delete all saved capsules? This cannot be undone.'))return;try{data.capsules=[];await saveData(data);toast('All capsules deleted')}catch(e){console.error(e);toast(e.message,true)}};
(async()=>{try{data=await getData();loadSettings()}catch(e){toast(e.message,true)}})();
